services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.tiny
    # IMPORTANT: Privileged mode is required to run a Docker daemon inside a container.
    # This grants the container extensive access to the host.
    privileged: true
    ports:
      - "8000:8000"
      - "2223:22"
    volumes:
      # This named volume will persist the data (images, containers, etc.)
      # of the *inner* Docker daemon across container restarts.
      - dind-storage:/var/lib/docker
    restart: unless-stopped
    healthcheck:
      # Command to check if the API server is responsive
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dind-storage:
